version: '3.8'

services:
  backend:
    container_name: FastAPI
    build:
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    networks:
      - appNetwork

  database:
    container_name: Postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local
    volumes:
      - postgresVolume:/var/lib/postgresql/data
    networks:
      - appNetwork

volumes:
  postgresVolume:

networks:
  appNetwork:
    driver: bridge
